AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources: 
  SSRFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/ssr
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 900 