# Generated by Django 4.1.3 on 2023-03-04 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modules.crawler.models.utils
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_gen,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="crawler.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupProduct",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_generator,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=256)),
                ("description", models.TextField(blank=True, default="")),
                ("list_image", models.TextField(blank=True, default="")),
                ("meta", models.JSONField(default=dict)),
                (
                    "store_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "largest_price",
                    models.FloatField(blank=True, db_index=True, default=0, null=True),
                ),
                (
                    "smallest_price",
                    models.FloatField(blank=True, db_index=True, default=0, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Product",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Scraper",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_gen,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "scheduler_type",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                        ],
                        default="once",
                        max_length=50,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("start_date", models.DateField()),
                ("job_id", models.CharField(max_length=256)),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WareParser",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_gen,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sitemap",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_gen,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "crawl_type",
                    models.CharField(
                        choices=[("mpa", "MPA"), ("spa", "SPA")],
                        default="mpa",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("base_url", models.CharField(max_length=256)),
                (
                    "target_search_terms",
                    models.CharField(
                        blank=True,
                        default="apple-iphone-,iphone-14,iphone-13,iphone-12,iphone-11,iphone-se",
                        max_length=512,
                    ),
                ),
                (
                    "exclude_search_terms",
                    models.CharField(
                        blank=True,
                        default="dat-truoc,su-kien,event,quay-,tai-nghe,&,filter,loc,so-sanh,san-pham-moi,cong-nghe,nguoi-,khuyen-mai,phu-kien,combo,tag,dchannel,tragop,zalo,tra-gop,news,tekzone,the-,hub-,cap-,cuong-luc,bao-,mieng-,sac-,op-,mua-",
                        max_length=512,
                    ),
                ),
                (
                    "is_sitemap_running",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "is_crawl_detail_running",
                    models.BooleanField(default=False, editable=False),
                ),
                ("category_name", models.CharField(default="", max_length=256)),
                ("limit_page", models.CharField(default="500", max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ware_parser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.wareparser",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScraperSitemap",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_generator,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scraper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.scraper",
                    ),
                ),
                (
                    "sitemap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.sitemap",
                    ),
                ),
            ],
            options={
                "ordering": ["sitemap"],
            },
        ),
        migrations.AddField(
            model_name="scraper",
            name="sitemap_cells",
            field=models.ManyToManyField(
                through="crawler.ScraperSitemap", to="crawler.sitemap"
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_generator,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("base_url", models.CharField(default="", max_length=1024)),
                ("name", models.CharField(max_length=1024)),
                ("title", models.CharField(max_length=1024)),
                ("encoded_base_url", models.CharField(max_length=1024)),
                (
                    "price",
                    models.FloatField(blank=True, db_index=True, default=0, null=True),
                ),
                (
                    "list_price",
                    models.FloatField(blank=True, db_index=True, default=0, null=True),
                ),
                (
                    "discount_rate",
                    models.IntegerField(
                        blank=True, db_index=True, default=0, null=True
                    ),
                ),
                ("is_subscribe", models.BooleanField(db_index=True, default=True)),
                ("is_used", models.BooleanField(db_index=True, default=False)),
                (
                    "last_updated_price",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("meta", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True, default="")),
                ("list_image", models.TextField(blank=True, default="")),
                (
                    "count_update",
                    models.IntegerField(default=1, verbose_name="Count Update"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.category",
                    ),
                ),
                (
                    "group_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.groupproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["group_product__name"],
            },
        ),
        migrations.CreateModel(
            name="Parser",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_generator,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "selector_type",
                    models.CharField(
                        choices=[("xpath", "XPATH"), ("css", "CSS")],
                        default="xpath",
                        max_length=50,
                    ),
                ),
                ("selector", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ware_parser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsers",
                        to="crawler.wareparser",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PageInfo",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_generator,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("url", models.CharField(max_length=512)),
                ("title", models.CharField(max_length=512)),
                ("encoded_base_url", models.CharField(max_length=512)),
                ("meta", models.JSONField(default=dict)),
                ("count_update", models.IntegerField(default=1, editable=False)),
                ("is_subscribe", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sitemap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.sitemap",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="HistoryPricing",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_generator,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("price", models.FloatField(blank=True, default=0, null=True)),
                ("list_price", models.FloatField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.product",
                    ),
                ),
            ],
        ),
    ]
