# Generated by Django 3.2.15 on 2023-01-04 14:25

from django.db import migrations, models
import django.db.models.deletion
import modules.crawler.models.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_gen, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('scheduler_type', models.CharField(choices=[('once', 'Once'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='once', max_length=50)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('job_id', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_gen, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('crawl_type', models.CharField(choices=[('mpa', 'MPA'), ('spa', 'SPA')], default='mpa', max_length=50)),
                ('name', models.CharField(max_length=256)),
                ('base_url', models.CharField(max_length=256)),
                ('limit_page', models.CharField(default='1', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WareParser',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_gen, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperSitemap',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_generator, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.scraper')),
                ('sitemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.sitemap')),
            ],
        ),
        migrations.AddField(
            model_name='scraper',
            name='sitemap_cells',
            field=models.ManyToManyField(through='crawler.ScraperSitemap', to='crawler.Sitemap'),
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_generator, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('selector_type', models.CharField(choices=[('xpath', 'XPATH'), ('css', 'CSS')], default='xpath', max_length=50)),
                ('selector', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.wareparser')),
            ],
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_generator, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('encoded_base_url', models.CharField(max_length=512)),
                ('meta', models.JSONField(default=dict)),
                ('count_update', models.IntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sitemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.sitemap')),
            ],
        ),
    ]
