# Generated by Django 3.2.15 on 2023-01-02 15:03

from django.db import migrations, models
import django.db.models.deletion
import modules.crawler.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_gen, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('base_url', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.CharField(default='25540966', editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('h1', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sitemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.sitemap')),
            ],
        ),
    ]
