# Generated by Django 3.2.15 on 2022-09-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='domain',
            field=models.TextField(null=True),
        ),
    ]
