# Generated by Django 3.2.15 on 2022-10-01 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="id_raw_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crawler.rawproduct",
            ),
        ),
    ]
