# Generated by Django 3.2.15 on 2022-09-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='is_using_proxy',
            field=models.BooleanField(default=True, verbose_name='Using Proxy'),
        ),
    ]
