# Generated by Django 3.2.15 on 2023-01-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='target_search_terms',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
