# Generated by Django 3.2.15 on 2022-09-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_spider_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='domain',
            field=models.CharField(default='', max_length=256, verbose_name='domain'),
        ),
    ]
