# Generated by Django 3.2.15 on 2022-09-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_spider_is_using_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='agency',
            field=models.CharField(blank=True, max_length=512, verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='is_using_proxy',
            field=models.BooleanField(default=False, verbose_name='Using Proxy'),
        ),
    ]
