# Generated by Django 3.2.15 on 2022-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_product_id_raw_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count_update",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rawproduct",
            name="count_update",
            field=models.IntegerField(default=0),
        ),
    ]
