# Generated by Django 3.2.15 on 2022-09-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_spider_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=516, verbose_name='URL')),
                ('base_encoded_url', models.CharField(max_length=516, verbose_name='Encode URL')),
                ('data_str', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='spider',
            name='url',
            field=models.CharField(max_length=516, verbose_name='URL'),
        ),
    ]
