# Generated by Django 3.2.15 on 2023-01-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20230102_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='crawl_type',
            field=models.CharField(choices=[('mpa', 'MPA'), ('spa', 'SPA')], default='mpa', max_length=50),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='id',
            field=models.CharField(default='19513262', editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='id',
            field=models.CharField(default='165055', editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scrapersitemap',
            name='id',
            field=models.CharField(default='166138', editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
