# Generated by Django 3.2.15 on 2023-01-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20230105_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parser',
            old_name='spider',
            new_name='ware_parser',
        ),
    ]
