# Generated by Django 3.2.15 on 2022-09-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20220925_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('address', models.CharField(default='', max_length=256)),
                ('agency', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='base_encoded_url',
            field=models.CharField(max_length=512, verbose_name='Encode URL'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='url',
            field=models.CharField(max_length=512, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='spider',
            name='url',
            field=models.CharField(max_length=512, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('clean_name', models.CharField(max_length=256, verbose_name='Clean Name')),
                ('url', models.CharField(max_length=512, verbose_name='URL')),
                ('base_encoded_url', models.CharField(max_length=512, verbose_name='Encode URL')),
                ('domain', models.CharField(max_length=256, verbose_name='Domain')),
                ('agency', models.CharField(max_length=256, verbose_name='Agency')),
                ('product_code', models.CharField(max_length=256, verbose_name='Code')),
                ('is_api', models.BooleanField(default=True, verbose_name='From API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug_id', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('stock', models.TextField(null=True)),
                ('item_rating', models.TextField(null=True)),
                ('historical_sold', models.TextField(null=True)),
                ('liked_count', models.TextField(null=True)),
                ('price', models.TextField(null=True)),
                ('list_price', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('score', models.TextField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.shop')),
            ],
        ),
    ]
