# Generated by Django 3.2.15 on 2022-09-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20220925_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.TextField(null=True),
        ),
    ]
