# Generated by Django 3.2.15 on 2022-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0005_auto_20221001_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawproduct",
            name="scraper_type",
            field=models.CharField(
                choices=[("api", "API"), ("html", "HTML")], default="api", max_length=50
            ),
        ),
    ]
