# Generated by Django 3.2.15 on 2022-10-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0006_rawproduct_scraper_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="spider",
            name="is_running",
            field=models.BooleanField(default=False, verbose_name="Is running"),
        ),
    ]
