# Generated by Django 3.2.15 on 2023-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_alter_parser_ware_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
