# Generated by Django 3.2.15 on 2023-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_pageinfo_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinfo',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
