# Generated by Django 3.2.15 on 2022-10-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0007_spider_is_running"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug_id",
            field=models.CharField(blank=True, max_length=1024, verbose_name="Slug Id"),
        ),
        migrations.AlterField(
            model_name="spider",
            name="is_running",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Is running"
            ),
        ),
    ]
