# Generated by Django 3.2.15 on 2023-01-05 17:10

from django.db import migrations, models
import django.db.models.deletion
import modules.crawler.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_auto_20230105_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_gen, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_generator, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('list_image', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=modules.crawler.models.utils.id_generator, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('encoded_base_url', models.CharField(max_length=512)),
                ('meta', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('list_image', models.TextField(blank=True, default='')),
                ('price', models.CharField(blank=True, default='', max_length=100)),
                ('list_price', models.CharField(blank=True, default='', max_length=100)),
                ('count_update', models.IntegerField(default=0, verbose_name='Count Update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.category')),
                ('group_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.groupproduct')),
            ],
        ),
    ]
