# Generated by Django 3.2.15 on 2022-10-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0008_auto_20221002_0420"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupproduct",
            name="id_pcw",
            field=models.CharField(default="", max_length=20),
        ),
    ]
