# Generated by Django 3.2.15 on 2022-09-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_groupcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.groupcategory'),
        ),
    ]
