# Generated by Django 3.2.15 on 2022-10-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0009_groupproduct_id_pcw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupproduct",
            name="id_pcw",
        ),
        migrations.AddField(
            model_name="product",
            name="id_pcw",
            field=models.CharField(default="", max_length=20),
        ),
    ]
