# Generated by Django 3.2.15 on 2022-09-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_product_group_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupCategory',
            new_name='GroupProduct',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='group_category',
            new_name='group_product',
        ),
    ]
