# Generated by Django 3.2.15 on 2023-01-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_category_groupproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='category',
            field=models.CharField(default='', max_length=256),
        ),
    ]
