# Generated by Django 3.2.15 on 2022-09-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20220927_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproduct',
            name='list_product_ids_1',
            field=models.ManyToManyField(related_name='_crawler_groupproduct_list_product_ids_1_+', to='crawler.GroupProduct'),
        ),
    ]
