# Generated by Django 3.2.15 on 2022-10-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0010_auto_20221002_0424"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_api",
        ),
        migrations.AddField(
            model_name="product",
            name="scraper_type",
            field=models.CharField(
                choices=[("api", "API"), ("html", "HTML")], default="api", max_length=50
            ),
        ),
    ]
