# Generated by Django 3.2.15 on 2023-01-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_sitemap_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemap',
            old_name='category',
            new_name='category_name',
        ),
    ]
