# Generated by Django 3.2.15 on 2023-01-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_rename_category_sitemap_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
