# Generated by Django 3.2.15 on 2023-01-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_product_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.groupproduct'),
        ),
    ]
