# Generated by Django 3.2.15 on 2022-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0012_spider_class_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="spider",
            name="class_child",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Class Child"
            ),
        ),
    ]
