# Generated by Django 3.2.15 on 2022-10-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0013_spider_class_child"),
    ]

    operations = [
        migrations.AddField(
            model_name="spider",
            name="is_headless",
            field=models.BooleanField(default=False, verbose_name="Using browser"),
        ),
    ]
