# Generated by Django 3.2.15 on 2022-09-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_groupproduct_list_product_ids_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupproduct',
            name='list_product_ids_1',
        ),
    ]
