# Generated by Django 3.2.15 on 2022-10-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_spider_is_headless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='is_headless',
            field=models.BooleanField(default=True, verbose_name='Not using browser'),
        ),
    ]
