# Generated by Django 3.2.15 on 2023-01-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_auto_20230105_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupproduct',
            options={'verbose_name': 'Group Product'},
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
