# Generated by Django 3.2.15 on 2022-09-27 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0016_alter_groupproduct_product_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='product_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), default=list, size=1000),
        ),
    ]
