# Generated by Django 4.1.3 on 2023-01-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0017_auto_20230107_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="list_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
