# Generated by Django 3.2.15 on 2022-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0017_auto_20220927_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawproduct',
            name='data_str',
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='agency',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
