# Generated by Django 3.2.15 on 2022-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0018_auto_20220927_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='shop',
            name='agency',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
