# Generated by Django 4.1.3 on 2023-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0018_alter_product_list_price_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_rate",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
