# Generated by Django 4.1.3 on 2023-01-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0019_product_discount_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_rate",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
