# Generated by Django 3.2.15 on 2022-09-27 15:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0019_auto_20220927_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='agency',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), default=list, size=100),
        ),
    ]
