# Generated by Django 4.1.3 on 2023-01-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0020_alter_product_discount_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_subscribe",
            field=models.BooleanField(default=True),
        ),
    ]
