# Generated by Django 3.2.15 on 2022-09-27 15:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0020_alter_groupproduct_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupproduct',
            name='agency',
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='agencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=10), default=list, size=100),
        ),
    ]
