# Generated by Django 3.2.15 on 2022-09-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0022_auto_20220927_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
    ]
