# Generated by Django 4.1.3 on 2023-01-28 07:47

from django.db import migrations, models
import django.db.models.deletion
import modules.crawler.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0022_product_is_used"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryPricing",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=modules.crawler.models.utils.id_generator,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("price", models.FloatField(blank=True, default=0, null=True)),
                ("list_price", models.FloatField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.product",
                    ),
                ),
            ],
        ),
    ]
