# Generated by Django 4.1.3 on 2023-01-28 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0023_historypricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_updated_price",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
