# Generated by Django 3.2.15 on 2022-09-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0023_remove_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
