# Generated by Django 4.1.3 on 2023-01-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0024_product_last_updated_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="last_updated_price",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
