# Generated by Django 3.2.15 on 2022-10-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0025_category_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='spiders',
            field=models.ManyToManyField(null=True, through='crawler.ScraperSpider', to='crawler.Spider'),
        ),
    ]
