# Generated by Django 4.1.3 on 2023-01-28 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0025_alter_product_last_updated_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historypricing",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
