# Generated by Django 4.1.3 on 2023-01-29 08:09

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0026_alter_historypricing_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent_category",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="crawler.category",
            ),
        ),
    ]
