# Generated by Django 4.1.3 on 2023-01-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0029_category_level_category_lft_category_rght_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="parent_category",
            new_name="parent",
        ),
    ]
