# Generated by Django 3.2.15 on 2022-10-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0030_remove_product_id_pcw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupproduct",
            name="product_ids",
        ),
    ]
