# Generated by Django 3.2.15 on 2022-10-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0031_remove_groupproduct_product_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='spider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.spider'),
        ),
    ]
