# Generated by Django 4.1.3 on 2023-01-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0032_alter_category_options_alter_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupproduct",
            name="store_name",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
