# Generated by Django 3.2.15 on 2022-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0033_alter_rawproduct_spider'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='deepth',
            field=models.IntegerField(default=0, verbose_name='Deepth'),
        ),
    ]
