# Generated by Django 4.1.3 on 2023-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0033_groupproduct_store_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupproduct",
            name="largest_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="groupproduct",
            name="smallest_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
