# Generated by Django 3.2.15 on 2022-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0034_spider_deepth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='deepth',
            field=models.IntegerField(default=1, verbose_name='Deepth'),
        ),
    ]
