# Generated by Django 4.1.3 on 2023-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0035_alter_product_discount_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupproduct",
            name="largest_price",
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="groupproduct",
            name="name",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="groupproduct",
            name="smallest_price",
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="groupproduct",
            name="store_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=512
            ),
        ),
    ]
