# Generated by Django 3.2.15 on 2022-12-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0035_alter_spider_deepth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='historical_sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='liked_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='clean_slug_name',
            field=models.CharField(default='', max_length=512, verbose_name='Clean Slug Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='clean_name',
            field=models.CharField(max_length=512, verbose_name='Clean Name'),
        ),
    ]
