# Generated by Django 3.2.15 on 2022-12-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0036_auto_20221231_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=256, verbose_name='Brand'),
        ),
    ]
