# Generated by Django 4.1.3 on 2023-03-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0036_alter_groupproduct_largest_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="base_url",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="product",
            name="encoded_base_url",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=1024),
        ),
    ]
