# Generated by Django 3.2.15 on 2022-12-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0037_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='deepth',
        ),
        migrations.AddField(
            model_name='spider',
            name='search_term',
            field=models.CharField(default='', max_length=256, verbose_name='Search Term'),
        ),
    ]
