from modules.crawler.models.utils import id_gen
from modules.crawler.models import model_category
from modules.crawler.models import model_brand
from modules.crawler.models import model_parser
from modules.crawler.models import model_spider
from modules.crawler.models import model_product
from modules.crawler.models import model_raw_product
from modules.crawler.models import model_group_product
from modules.crawler.models import model_seller
